fix: missing printsupport include
Fixes problems with this compilation error: **Cannot open include file: 'QtPrintSupport': No such file or directory**
I'm using Qt Creator 3.5.1 & Qt 5.5.1 under Ubuntu 16.04 x64